package App;


/**
* App/BankTransactionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Final.idl
* Friday, October 30, 2015 5:49:59 PM CET
*/

public interface BankTransactionOperations 
{
  boolean askConfirm (int idAccountA, int idAccountB, int idBankA, int money);
  int getId ();
} // interface BankTransactionOperations
