package App;


/**
* App/BankCustomerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Final.idl
* Friday, October 30, 2015 5:49:59 PM CET
*/

public interface BankCustomerOperations 
{
  int createAccount (String accountname, int money);
  void destroy (int idAccount);
  boolean depositAccount (int idAccountA, int idAccountB, int idBank, int money);
  void withDrawAccount (int idAccountA, int money);
  int getMoney (int idAccountA);
} // interface BankCustomerOperations
