package App;


/**
* App/BankCustomerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Final.idl
* Friday, October 30, 2015 5:49:59 PM CET
*/

public abstract class BankCustomerPOA extends org.omg.PortableServer.Servant
 implements App.BankCustomerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createAccount", new java.lang.Integer (0));
    _methods.put ("destroy", new java.lang.Integer (1));
    _methods.put ("depositAccount", new java.lang.Integer (2));
    _methods.put ("withDrawAccount", new java.lang.Integer (3));
    _methods.put ("getMoney", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // App/BankCustomer/createAccount
       {
         String accountname = in.read_string ();
         int money = in.read_long ();
         int $result = (int)0;
         $result = this.createAccount (accountname, money);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // App/BankCustomer/destroy
       {
         int idAccount = in.read_long ();
         this.destroy (idAccount);
         out = $rh.createReply();
         break;
       }

       case 2:  // App/BankCustomer/depositAccount
       {
         int idAccountA = in.read_long ();
         int idAccountB = in.read_long ();
         int idBank = in.read_long ();
         int money = in.read_long ();
         boolean $result = false;
         $result = this.depositAccount (idAccountA, idAccountB, idBank, money);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // App/BankCustomer/withDrawAccount
       {
         int idAccountA = in.read_long ();
         int money = in.read_long ();
         this.withDrawAccount (idAccountA, money);
         out = $rh.createReply();
         break;
       }

       case 4:  // App/BankCustomer/getMoney
       {
         int idAccountA = in.read_long ();
         int $result = (int)0;
         $result = this.getMoney (idAccountA);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:App/BankCustomer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BankCustomer _this() 
  {
    return BankCustomerHelper.narrow(
    super._this_object());
  }

  public BankCustomer _this(org.omg.CORBA.ORB orb) 
  {
    return BankCustomerHelper.narrow(
    super._this_object(orb));
  }


} // class BankCustomerPOA
