package App;


/**
* App/InterbankHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Final.idl
* Friday, October 30, 2015 5:49:59 PM CET
*/

abstract public class InterbankHelper
{
  private static String  _id = "IDL:App/Interbank:1.0";

  public static void insert (org.omg.CORBA.Any a, App.Interbank that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static App.Interbank extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (App.InterbankHelper.id (), "Interbank");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static App.Interbank read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_InterbankStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, App.Interbank value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static App.Interbank narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof App.Interbank)
      return (App.Interbank)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      App._InterbankStub stub = new App._InterbankStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static App.Interbank unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof App.Interbank)
      return (App.Interbank)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      App._InterbankStub stub = new App._InterbankStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
