package App;


/**
* App/arrayStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Sunday, November 1, 2015 12:06:39 PM CET
*/

public final class arrayStringHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public arrayStringHolder ()
  {
  }

  public arrayStringHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.arrayStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.arrayStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.arrayStringHelper.type ();
  }

}
