package App;


/**
* App/BankCustomerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Sunday, November 1, 2015 12:06:39 PM CET
*/

public interface BankCustomerOperations 
{
  int createAccount (String accountname, int money);
  void destroy (int idAccount);
  boolean depositAccount (int idAccountA, int idAccountB, int idBank, int money);
  void withDrawAccount (int idAccountA, int money);
  int getMoney (int idAccountA);
  int getId ();
  boolean checkAuthentification (int id);
  String[] getHistory (int idAccount);
} // interface BankCustomerOperations
