package App;

/**
* App/BankCustomerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Saturday, October 31, 2015 5:45:03 PM CET
*/

public final class BankCustomerHolder implements org.omg.CORBA.portable.Streamable
{
  public App.BankCustomer value = null;

  public BankCustomerHolder ()
  {
  }

  public BankCustomerHolder (App.BankCustomer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.BankCustomerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.BankCustomerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.BankCustomerHelper.type ();
  }

}
