package App;


/**
* App/BankTransactionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Sunday, November 1, 2015 12:06:39 PM CET
*/

public interface BankTransactionOperations 
{
  boolean askConfirm (int idAccountA, int idAccountB, int idBankA, int money);
  int getId ();
} // interface BankTransactionOperations
