package App;


/**
* App/InterbankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Sunday, November 1, 2015 12:06:39 PM CET
*/

public interface InterbankOperations 
{
  boolean askTransfert (int idAccountA, int idAccountB, int idBankA, int idBankB, int money);
  int getNewId ();
  void addNewBank (int port, int id);
  String[] getHistory (int idBank, int idAccount);
} // interface InterbankOperations
