package App;

/**
* App/InterbankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from App.idl
* Saturday, October 31, 2015 5:45:03 PM CET
*/

public final class InterbankHolder implements org.omg.CORBA.portable.Streamable
{
  public App.Interbank value = null;

  public InterbankHolder ()
  {
  }

  public InterbankHolder (App.Interbank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = App.InterbankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    App.InterbankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return App.InterbankHelper.type ();
  }

}
